version: '2'

services:
  web:
    image: node:12.3.1-alpine
    container_name: portfolio2019
    volumes:
      - ./:/home/app
      - /home/app/node_modules
    working_dir: /home/app
    command: [sh, -c, npm install --global yarn && yarn global add gatsby-cli && yarn install && GATSBY_WEBPACK_PUBLICPATH=/ gatsby develop --host=0.0.0.0]
    ports:
      - "8000:8000"
      - "9000:9000"

